# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on:
      - self-hosted
      - la
    strategy:
      matrix:
        python_version: ["3.10"]

    steps:
      - uses: actions/checkout@v2
      - name: echo satement
        run: echo "Hello"
      # - name: Set up Python ${{ matrix.python_version }}
      #   uses: actions/setup-python@v3
      #   with:
      #     python-version: ${{ matrix.python_version }}
      # - uses: Gr1N/setup-poetry@v7
      #   with:
      #     poetry-version: 1.1.13
      - name: poetry version
        run: |
          poetry --version
      - run: poetry --version
      - run: poetry install
      - run: poetry run flake8
      - run: poetry run pytest
      - run: poetry run black --check --diff .
